- name: Setup snap
  ansible.builtin.package:
    name: snapd
    state: latest
  when: not ansible_check_mode

# We need to use LXD to support advanced networking
- name: From snap, setup multipass, lxd
  snap:
    name: 
    - multipass
    - lxd
    channel: "{{ linux_version }}"
    state: present
    classic: yes
  when: not ansible_check_mode
  