multipass_vms:
- name: microk8s-master
  template: microk8s-fel-master

multipass_vm_instances:
- name: microk8s-master0
  vcpu: 2
  disk: 80G
  mem: 4G
  networks: []
  cloud_init: microk8s.yaml
  state: running
