# Managed by Jsonnet. See $ROOT/coarse_config/felia.jsonnet
multipass_vm_instances:
  - cloud_init: microk8s.yaml
    disk: 20G
    mem: 3G
    name: microk8s-master0
    networks:
      - mode: auto
        name: Guest OS to Host OS
    state: deleted
    vcpu: 2
  - cloud_init: microk8s.yaml
    disk: 20G
    mem: 3G
    name: microk8s-master1
    networks:
      - mode: auto
        name: Guest OS to Host OS
    state: deleted
    vcpu: 2
  - cloud_init: microk8s-worker.yaml
    disk: 10G
    mem: 2G
    name: microk8s-worker0
    networks: []
    state: deleted
    vcpu: 2
  - cloud_init: microk8s-worker.yaml
    disk: 10G
    mem: 2G
    name: microk8s-worker1
    networks: []
    state: deleted
    vcpu: 2
  - cloud_init: microk8s-worker.yaml
    disk: 10G
    mem: 2G
    name: microk8s-worker2
    networks: []
    state: deleted
    vcpu: 2
