# Managed by Jsonnet. See $ROOT/coarse_config/templates.jsonnet
vm_templates:
  default:
    cloud_init: ""
    disk: 5G
    mem: 2G
    networks: []
    vcpu: 1
  microk8s-fel-master:
    cloud_init: microk8s.yaml
    disk: 20G
    mem: 3G
    networks:
      - mode: auto
        name: eth0
    vcpu: 2
  microk8s-master:
    cloud_init: microk8s.yaml
    disk: 20G
    mem: 3G
    networks:
      - mode: auto
        name: Guest OS to Host OS
    vcpu: 2
  microk8s-worker:
    cloud_init: microk8s-worker.yaml
    disk: 10G
    mem: 2G
    networks: []
    vcpu: 2
