---
- name: Setup multipass
  hosts: multipass:microk8s:microk8s_HA:microk8s_WORKERS
  tasks:
  - include_tasks: tasks/multipass.yml

- name: microk8s Felia
  hosts: felia
  tasks:
  - include_tasks: tasks/vm.yml
  vars:
    multipass_vms:
    - name: microk8s-master
      template: microk8s-master
      replicas: 2
    - name: microk8s-worker
      template: microk8s-worker
      replicas: 3

- name: microk8s Fel
  hosts: fel
  tasks:
  - include_tasks: tasks/vm.yml
  vars:
    multipass_vms:
    - name: microk8s-master
      template: microk8s-fel-master
